### ISSUE TITLE
Great plugin!

### ISSUE THREAD

**Issue by cukal** [theasp/ansible-inventory-yaml-groups#1]
This is really great plugin, thanks for it! 

I have several hosts that require the same set of specific host variables. Is it possible to create a group and assign variables at the group level? Assigning them at the host level they need to be repeated for every host.

I tried this but it didn't seem to work: 

```yaml
groups:
  GROUP_NAME:
    require:
      - GROUP1
      - GROUP2
    vars:
      foo: bar 
```

**Comment by theasp** [comment]
Thanks for the interest!

I think `include` will do what you want, which will add all hosts from the named groups.  `require` will remove any hosts from a group that are not a member of one of the listed groups,  The following will make the group `home_desktops`, using all hosts in `loc_home`, that are also in `type_desktop`:

```yaml
groups:
  home_desktops:
    include:
      - loc_home
    require:
      - type_desktop
    vars:
      some_var: some_value
```

Does this do what you are looking for?
